### ISSUE TITLE
`diffs` should never yield a negative time span

### ISSUE THREAD

**Issue by soenkehahn** [elm-lang/animation#6]
The very first time delta that comes out of `diffs` can sometimes be negative. If I understand `diffs` correctly, they should never be negative.

**Comment by lukewestby** [comment]
@soenkehahn can you create a http://sscce.org/ demonstrating this behavior and share it here?

**Comment by Soreine** [comment]
Should this be closed since #8 was merged and released?

**Comment by soenkehahn** [comment]
Sorry, I'm not working on an elm project that uses `animation-frame` anymore, so I don't have any stakes in this anymore. I'll close this issue. Please, re-open if you feel like it.
